<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Manufacturer extends Model
{
    use SoftDeletes;

    protected $fillable = ['name', 'description'];

    protected $dates = ['deleted_at'];

    public function products()
    {
        return $this->hasMany(Product::class);
    }
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        Manufacturer::deleting(function($manufacturer){
//            dd($manufacturer);
            foreach ($manufacturer->products as $product){
                $product->delete();
            }
        });
    }

}